### ISSUE TITLE
Problems finding this in Mod Browser

### ISSUE THREAD

**Issue by MrDj200** [0x0ade/TerrariaHooks#1] opened 2018-12-29 13:34 UTC
Hello, 
when I try to install mods that have this as dependency on my dedicated server, players can't connect and get the text "Mod terrariahooks not found".
Also when you press on the "!" icon on the mod in the server browser, it says "not found" (although thats not always the case)

Do you know any fixes for this, except manually installing it on every machine?

-Dj

**Comment by 0x0ade** [comment] 2018-12-29 15:03
Thanks for telling me about that!

That's caused by the standalone mod being `NoSync`. I've changed the `sync` back to `Both` for v0.14+ of the standalone mod.

It's not an issue with the future tML release with integrated TerrariaHooks.

v0.14 should be up on the mod browser soon. I'll close this issue - if there are any further issues, please open a new issue.

**Closed as completed by 0x0ade** 2018-12-29 15:03 UTC

**Comment by MrDj200** [comment] 2018-12-29 15:06
Thank you very much!
Have a nice day and a happy new year :)
